version: "3"
services:
  # mysql:
  #   image: mysql:5.7
  #   hostname: mysql
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_USER: karan
  #     MYSQL_PASSWORD: redhat
  #     MYSQL_DATABASE: redmine
  redmine:
    image: redmine:latest
    hostname: redmine
    restart: always
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - redmine:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_USERNAME: karan
      REDMINE_DB_PASSWORD: redhat
      REDMINE_DB_DATABASE: redmine
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
    # command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  mysql:
  redmine:
