version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    #environment:
    #  TZ: Asia/Tokyo # Please set time zone if you want to change it.
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      #NOTE : TLS key's path for HTTPS
      # - ./nginx/data/private/redminesgr.com+5.pem:/etc/ssl/private/redminesgr.crt
      # - ./nginx/data/certs/redminesgr.com+5-key.pem:/etc/ssl/certs/redminesgr.key
    hostname: nginx
    ports:
      - "3000:3000"
      - "443:443"
    links:
      - redmine
    depends_on:
      - redmine
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped
    extra_hosts:
      - "redminesgr.com:127.0.0.1"
      - "redminesgrapp.net:127.0.0.1"
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      #TZ: Asia/Tokyo # Please set time zone if you want to change it.
    volumes:
      - ./mariadb/config/my.cnf:/etc/mysql/my.cnf
      - ./storage/mariadb-storage/data:/var/lib/mysql
    hostname: mariadb
    expose:
      - "3306"
    command: mysqld
    restart: unless-stopped
  redmine:
    build:
      context: ./redmine
      dockerfile: Dockerfile
    container_name: redmine
    environment:
      RAILS_MIGRATE: 1
      PLUGINS_MIGRATE: 1
      DB_PING_USER: redmine
      DB_PING_USER_PASSWORD: redmine
      UNICORN_WORKER_PROCESS: 2
      UNICORN_TIMEOUT: 60
      # Unicorn worker killer settings. https://github.com/kzk/unicorn-worker-killer
      UNICORN_WOKER_KILLER_MEMORY_MIN: 192 # Memory min threshold. Unit is MB.
      UNICORN_WOKER_KILLER_MEMORY_MAX: 256 # Memory max threshold. Unit is MB.
      UNICORN_WOKER_KILLER_CHECK_CYCLE: 16
      UNICORN_WOKER_KILLER_VERBOSE: 0
      #TZ: Asia/Tokyo # Please set time zone if you want to change it.
    hostname: redmine
    expose:
      - "3000"
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - ./logs/redmine/:/usr/src/app/redmine/log/
      - ./storage/redmine-files/files:/usr/src/app/redmine/files
      - ./storage/git-storage/repositories:/usr/src/git
      # for configuration
      - ./redmine/src/config/configuration.yml:/usr/src/app/redmine/config/configuration.yml
      - ./redmine/src/config/database.yml:/usr/src/app/redmine/config/database.yml
      - ./redmine/src/config/unicorn.rb:/usr/src/app/redmine/config/unicorn.rb
      - ./redmine/src/config.ru:/usr/src/app/redmine/config.ru
      - ./redmine/src/public/themes:/usr/src/app/redmine/public/themes
      - ./redmine/src/plugins/:/usr/src/app/redmine/plugins/
      # TODO : Sync host machine's source code.
      #- ./redmine/redmine/app/:/usr/src/app/redmine/app/
    restart: unless-stopped
